# Generated by Django 4.0.4 on 2022-05-16 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('secondary_title', models.CharField(max_length=200)),
                ('edition', models.CharField(max_length=20)),
                ('author1', models.CharField(max_length=200)),
                ('author2', models.CharField(max_length=200)),
                ('author3', models.CharField(max_length=200)),
                ('rack', models.CharField(max_length=5)),
            ],
            options={
                'ordering': ['title', 'author1'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a book domain (e.g. Machine Learning, Data Science etc.)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LibUser',
            fields=[
                ('userid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-userid'],
            },
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('imprint', models.CharField(max_length=200)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('d', 'Maintenance'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], default='a', help_text='Book availability', max_length=1)),
                ('bookid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.book')),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.libuser')),
            ],
            options={
                'ordering': ['due_back'],
                'permissions': (('can_mark_returned', 'Set book as returned'),),
            },
        ),
        migrations.AddField(
            model_name='book',
            name='domain',
            field=models.ManyToManyField(help_text='Select a Domain for this book', to='catalog.domain'),
        ),
    ]
