# Generated by Django 4.0.4 on 2022-05-16 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libuser',
            name='contact',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='libuser',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
