# Generated by Django 4.0.4 on 2022-06-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renewal',
            name='id',
        ),
        migrations.AlterField(
            model_name='renewal',
            name='bookid',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
